import java.util.*;
public class TASK1 {

    public static void main(String[] args) {
        //Create Objects For Random and Scanner Classes
        Random Random = new Random();
        Scanner sc = new Scanner(System.in);
        System.out.println("GUESS THE NUMBER:\n\nABOUT GAME:\nThe System generates a random number between 1 and 100\nThe user gets 3 chances to guess the number and starts with an initial points of 30\nIf the guess is correct, the user is declared as winner with the points on dashboard\nFor every wrong attempt 10 points will be deducted from the dashboard.\n");
        //Initialise Variables
        int randInt , guess , chances , score;
        char ch;
        do{
            //Generate Random Number And Store In Variable randInt
            randInt = (1+Random.nextInt(99));
            System.out.println("\nRandom Number Generated By System!!");
            //Declare Chances and Initial Score
            chances = 3;
            score = 30;
            while(chances > 0){
                //Get Guess Value As Input From User
                System.out.println("\nEnter Guess(1-100) : ");
                guess = sc.nextInt();
                //Implement Calculation Algorithm and Conditions
                if(guess == randInt){
                    System.out.format("\nThe Guess Was Correct!!!\nSCORE : %d",score);
                    break;
                }
                else{
                    if(guess < randInt){
                        chances--;
                        score -= 10;
                        System.out.format("\nWrong Guess!\nGUESS IS LESS THAN THE VALUE\nTry Again\nREMAINING CHANCES : %d",chances);
                    }
                    else if(guess>randInt){
                        chances--;
                        score -= 10;
                        System.out.format("\nWrong Guess!\nGUESS IS HIGHER THAN THE VALUE\nTry Again\nREMAINING CHANCES : %d",chances);
                    }
                }
            }
            if(chances == 0){
                System.out.format("\nYou Lost The Game!!\nRANDOM NUMBER : %d\nSCORE : %d",randInt,score);
            }
            //New Game Option
            System.out.println("\nDo you want to play again(YES(y)/NO(n)) : ");
            ch=sc.next().charAt(0);
        }while(ch == 'y');    
    }
}